#!/bin/sh

echo "Start" > res;
for i in t25 t50 t75 t100 t125 t150 t175 t200 t225 t250;
 do 
   echo $i; 
   cd $i; make clean;
   echo $i >> ../res; echo "" >> ../res;
   make res; 
   cat res >> ../res; 
   cd ..; 
done
echo "End" >> res




